# Use root/example as user/password credentials
version: '3.9'

volumes:
    mysql_volume:

services:

  mysql:
    image: mysql
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass      
      MYSQL_DATABASE: CheapFlights
    volumes:
      - ./mysql_volume:/var/lib/mysql
      - ../init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-ppass"]
      interval: 30s
      timeout: 10s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 10000:8080

  app:
    image: flamehorizon/flight-scanner-arm64:latest
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
     mysql:
        condition: service_healthy

